### ISSUE TITLE
Double check v40

### ISSUE THREAD

**Issue by edspark** [sparkfun/Arduino_ProtoShield_Bare_PCB#16]
1) Is the version number correct? [NO]
comment: Change to v40.

2) Is there a correct version number in the copper (aligned properly with the edge of the PCB)? [NO]
comment: Change to v40.

Everything looked good but since the revision is going to REDs, it's time to change the version number on both schematic and PCB!

**Comment by bboyho** [comment]
@edspark 

I updated the schematic and board to say v40. I also updated the file names. =)

[https://github.com/sparkfun/Arduino_ProtoShield_Bare_PCB/pull/17](https://github.com/sparkfun/Arduino_ProtoShield_Bare_PCB/pull/17)
